# Generated by Django 4.2.11 on 2024-09-15 12:56

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    # Get the Categories model from the historical version
    Categories = apps.get_model('auctions', 'Categories')

    # List of initial categories to add
    initial_categories = [
        'Electronics',
        'Books',
        'Clothing',
        'Toys',
        'Jewelry & Watches',
        'Collectibles',
        'Sports & Outdoors',
    ]

    # Create each category
    for category_name in initial_categories:
        Categories.objects.create(name=category_name)


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
