# Generated by Django 4.2.11 on 2024-09-15 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20240915_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initial_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
