# Generated by Django 4.2.11 on 2024-09-16 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_winners_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
