# Generated by Django 4.2.11 on 2024-09-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/photos'),
        ),
    ]
