# Generated by Django 4.2.11 on 2024-09-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_categories_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name': 'Bids', 'verbose_name_plural': 'Bids'},
        ),
    ]
