# Generated by Django 4.2.11 on 2024-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bids_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='photo',
        ),
        migrations.AddField(
            model_name='listings',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
